"""init Migration

Revision ID: cb5f327669ec
Revises: 853655aef571
Create Date: 2023-03-04 03:08:53.346177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5f327669ec'
down_revision = '853655aef571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogDB', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogDB', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
